#!/usr/bin/env python

import sys
import time
import urllib2

try:
    import json
except ImportError:
    import simplejson as json

def exit_fn(prefix, return_code):
    def fn(msg):
        print "%s: %s" % (prefix, msg)
        sys.exit(return_code)
    return fn

exit_ok = exit_fn('OK', 0)
exit_warning = exit_fn('WARNING', 1)
exit_critical = exit_fn('CRITICAL', 2)

def main(api_key, interval, warning, critical):
    url = 'http://api.keyerror.com/v1/errors/recent/%d' % int(interval)

    request = urllib2.Request(url, headers={
        'X-API-Key': api_key,
    })

    data = json.loads(urllib2.urlopen(request).read())

    num = data['num_errors']

    msg = "Number of errors in the last %s seconds: %d" % (interval, num)

    if num >= int(critical):
        exit_critical(msg)
    if num >= int(warning):
        exit_warning(msg)

    exit_ok(msg)

if __name__ == '__main__':
    if len(sys.argv) != 5:
        exit_critical("usage: <api_key> <interval> <warning> <critical>")

    try:
        main(*sys.argv[1:])
    except Exception, e:
        exit_critical(e)
